spring.main.banner-mode=off
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration

spring.datasource.driver-class-name=tech.ydb.jdbc.YdbDriver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=120000

ydb.transaction.retry.enabled=true
ydb.transaction.retry.max-retries=10
ydb.transaction.retry.slow-backoff-base-ms=50
ydb.transaction.retry.fast-backoff-base-ms=5
ydb.transaction.retry.slow-cap-backoff-ms=5000
ydb.transaction.retry.fast-cap-backoff-ms=500
ydb.transaction.retry.idempotent=true

logging.level.root=warn
logging.level.tech.ydb.retry=info
logging.level.tech.ydb.slo=info
