{
 "title": "SLO",
 "tags": [ "slo" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "SLO Operations RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(sdk_operations_total[$__rate_interval]) > 0",
     "legendFormat": "{{sdk}}-{{sdk_version}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "In-flight Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sdk_pending_operations",
     "legendFormat": "{{sdk}}-{{sdk_version}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Success vs Failures RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(sdk_operations_success_total[$__rate_interval])",
     "legendFormat": "{{sdk}}-{{sdk_version}} {{operation_type}} success"
    },
    {
     "expr": "rate(sdk_operations_total[$__rate_interval]) - rate(sdk_operations_success_total[$__rate_interval])",
     "legendFormat": "{{sdk}}-{{sdk_version}} {{operation_type}} not_ok"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Read Latencies (OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"read\", operation_status=\"success\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"read\", operation_status=\"success\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"read\", operation_status=\"success\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"read\", operation_status=\"success\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Write Latencies (OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"write\", operation_status=\"success\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"write\", operation_status=\"success\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"write\", operation_status=\"success\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"write\", operation_status=\"success\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Read Latencies (NOT OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"read\", operation_status=\"failure\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"read\", operation_status=\"failure\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Write Latencies (NOT OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"write\", operation_status=\"failure\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(sdk_operation_latency_seconds_bucket{operation_type=\"write\", operation_status=\"failure\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}